version: '3'
services:
  red-tetris:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - '8080:8080'
      - '3000:3000'
