module.exports = {
  /* Socket events */

  CONNECT: 'connect',
  CONNECT_ERROR: 'connect_error',
  CONNECT_TIMEOUT: 'connect_timeout',
  RECONNECT: 'reconnect',
  RECONNECT_ATTEMPT: 'reconnect_attempt',
  RECONNECTING: 'reconnecting',
  RECONNECT_ERROR: 'reconnect_error',
  RECONNECT_FAILED: 'reconnect_failed',
  DISCONNECT: 'disconnect',

  /* App events */

  CLIENT_CONNECTING: 'CLIENT_CONNECT',
  CLIENT_CONNECT: 'CLIENT_CONNECTED',
  CLIENT_CONNECT_ERROR: 'CLIENT_CONNECT_ERROR',
  CLIENT_CONNECT_TIMEOUT: 'CLIENT_CONNECT_TIMEOUT',
  CLIENT_RECONNECT: 'CLIENT_RECONNECT',
  CLIENT_RECONNECT_ATTEMPT: 'CLIENT_RECONNECT_ATTEMPT',
  CLIENT_RECONNECTING: 'CLIENT_RECONNECTING',
  CLIENT_RECONNECT_ERROR: 'CLIENT_RECONNECT_ERROR',
  CLIENT_RECONNECT_FAILED: 'CLIENT_RECONNECT_FAILED',
  CLIENT_DISCONNECT: 'CLIENT_DISCONNECT',

  /* App events */

  req_UPDATE_APP_INFOS: '#INFOS',
  res_UPDATE_APP_INFOS: '@INFOS',
  req_LOGIN: '#LOGIN',
  res_LOGIN: '@LOGIN',
  req_LOGOUT: '#LOGOUT',
  res_LOGOUT: '@LOGOUT',

  /* Game event */

  req_UPDATE_GAME: '#UPDATE_GAME',
  res_UPDATE_GAME: '@UPDATE_GAME',
  req_UPDATE_GAME_OWNER: '#UPDATE_GAME_OWNER',
  res_UPDATE_GAME_OWNER: '@UPDATE_GAME_OWNER',
  res_UPDATE_GAME_PLAYERS: '@UPDATE_GAME_PLAYERS',
  req_UPDATE_GAME_SETTINGS: '#UPDATE_GAME_SETTINGS',
  res_UPDATE_GAME_SETTINGS: '@UPDATE_GAME_SETTINGS',
  req_UPDATE_GAME_CHAT: '#UPDATE_GAME_CHAT',
  res_UPDATE_GAME_CHAT: '@UPDATE_GAME_CHAT',
  req_START_GAME: '#START_GAME',
  res_START_GAME: '@START_GAME',

  /* Player events */

  req_UPDATE_PLAYER: '#UPDATE_PLAYER',
  res_UPDATE_PLAYER: '@UPDATE_PLAYER',

  /* App actions */

  UPDATE_CONNECTION: 'UPDATE_CONNECTION',
  UPDATE_LOG: 'UPDATE_LOG',
  UPDATE_INFOS: 'UPDATE_INFOS',

  /* Game actions */

  UPDATE_GAME: 'UPDATE_GAME',
  UPDATE_GAME_SETTINGS: 'UPDATE_GAME_SETTINGS',
  UPDATE_GAME_PLAYERS: 'UPDATE_GAME_PLAYERS',
  UPDATE_GAME_CHAT: 'UPDATE_GAME_CHAT',

  /* Player actions */

  UPDATE_PLAYER: 'UPDATE_PLAYER',
};
